version: "3.0"
services:
  elasticsearch:
    container_name: elastic-search
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - elastic
    ports:
      - 9200:9200
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:6.6.1
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    networks:
      - elastic
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
networks:
  elastic:
    driver: bridge
